/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import controle.TurmaDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Professor;
import modelo.Turma;

/**
 *
 * @author Usuario
 */
public class TelaProfessor extends javax.swing.JFrame {
private Professor professorLogado;
private Turma turma;
    /**
     * Creates new form TelaProfessor
     */
    public TelaProfessor(Professor logado) {
        initComponents();
        
    this.professorLogado = logado;
    listarTurmas();
   
    txtNomeProfessor.setEditable(false);
    txtNomeProfessor.setText(professorLogado.getNome());

    
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel01_TelaProfessor = new javax.swing.JPanel();
        jPanel02_TelaProfessor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTurma = new javax.swing.JTable();
        btnCdastrarTurma = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        txtNomeProfessor = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel01_TelaProfessor.setBackground(new java.awt.Color(0, 102, 255));
        jPanel01_TelaProfessor.setForeground(new java.awt.Color(0, 102, 255));

        jPanel02_TelaProfessor.setBackground(new java.awt.Color(255, 255, 255));
        jPanel02_TelaProfessor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero", "Nome"
            }
        ));
        jScrollPane1.setViewportView(tabelaTurma);

        jPanel02_TelaProfessor.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 580, 330));

        btnCdastrarTurma.setBackground(new java.awt.Color(0, 102, 255));
        btnCdastrarTurma.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        btnCdastrarTurma.setForeground(new java.awt.Color(255, 255, 255));
        btnCdastrarTurma.setText("Cadastrar Turma");
        btnCdastrarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCdastrarTurmaActionPerformed(evt);
            }
        });
        jPanel02_TelaProfessor.add(btnCdastrarTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 130, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Turmas:");
        jPanel02_TelaProfessor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        btnExcluir.setBackground(new java.awt.Color(0, 102, 255));
        btnExcluir.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel02_TelaProfessor.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnVisualizar.setBackground(new java.awt.Color(0, 102, 255));
        btnVisualizar.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        btnVisualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        jPanel02_TelaProfessor.add(btnVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        txtNomeProfessor.setBackground(new java.awt.Color(0, 102, 255));
        txtNomeProfessor.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtNomeProfessor.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeProfessor.setBorder(null);
        txtNomeProfessor.setFocusable(false);
        txtNomeProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProfessorActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(0, 102, 255));
        btnSair.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.setBorder(null);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel01_TelaProfessorLayout = new javax.swing.GroupLayout(jPanel01_TelaProfessor);
        jPanel01_TelaProfessor.setLayout(jPanel01_TelaProfessorLayout);
        jPanel01_TelaProfessorLayout.setHorizontalGroup(
            jPanel01_TelaProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel01_TelaProfessorLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel01_TelaProfessorLayout.createSequentialGroup()
                .addComponent(jPanel02_TelaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel01_TelaProfessorLayout.setVerticalGroup(
            jPanel01_TelaProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel01_TelaProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel01_TelaProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel02_TelaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel01_TelaProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel01_TelaProfessor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProfessorActionPerformed
       
    }//GEN-LAST:event_txtNomeProfessorActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
             // TODO add your handling code here:
             
          TelaLogin l = new TelaLogin();
          l.setVisible(true);
          
          this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCdastrarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCdastrarTurmaActionPerformed
        
        TelaCadastroTurma t = new TelaCadastroTurma(professorLogado);
        t.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnCdastrarTurmaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        
        int linhaSelecionada = tabelaTurma.getSelectedRow();

    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione uma turma na tabela para excluir.");
        return;
    }

    
    int idTurma = Integer.parseInt(tabelaTurma.getValueAt(linhaSelecionada, 0).toString());


    try {
        TurmaDAO dao = new TurmaDAO();

        if (dao.turmaTemAtividades(idTurma)) {
            JOptionPane.showMessageDialog(this, "Não é possível excluir a turma. Existem atividades cadastradas.");
            return;
        }

        int opcao = JOptionPane.showConfirmDialog(this,
            "Deseja realmente excluir esta turma?", "Confirmação", JOptionPane.YES_NO_OPTION);

        if (opcao == JOptionPane.YES_OPTION) {
            dao.excluirTurma(idTurma);
            listarTurmas();
            JOptionPane.showMessageDialog(this, "Turma excluída com sucesso!");
             
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao excluir turma: " + e.getMessage());
    }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        // TODO add your handling code here:
        
        int linhaSelecionada = tabelaTurma.getSelectedRow();
        if (linhaSelecionada != -1) {
        int idTurma = (int) tabelaTurma.getValueAt(linhaSelecionada, 0);
        String nomeTurma = (String) tabelaTurma.getValueAt(linhaSelecionada, 1);

         Turma turmaSelecionada = new Turma();
         turmaSelecionada.setIdturma(idTurma);
         turmaSelecionada.setNome(nomeTurma);
         turmaSelecionada.setProfessor(professorLogado); 

         TelaAtividade telaAtividades = new TelaAtividade(turmaSelecionada);
         telaAtividades.setVisible(true);
         this.dispose();
      }        else {
        JOptionPane.showMessageDialog(this, "Selecione uma turma.");
      }

    }//GEN-LAST:event_btnVisualizarActionPerformed
    
    private void listarTurmas() {
    try {
        TurmaDAO dao = new TurmaDAO();
        List<Turma> lista = dao.listarTurma(professorLogado.getIdProfessor());

        DefaultTableModel modelo = (DefaultTableModel) tabelaTurma.getModel();
        modelo.setRowCount(0); // limpa a tabela

        for (Turma t : lista) {
            modelo.addRow(new Object[]{t.getIdturma(), t.getNome()});
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar turmas: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCdastrarTurma;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel01_TelaProfessor;
    private javax.swing.JPanel jPanel02_TelaProfessor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaTurma;
    private javax.swing.JTextField txtNomeProfessor;
    // End of variables declaration//GEN-END:variables
}
