/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import controle.AtividadeDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Atividade;
import modelo.Professor;
import modelo.Turma;

/**
 *
 * @author Usuario
 */
public class TelaAtividade extends javax.swing.JFrame {
private Turma turmaSelecionada;
private Professor professorLogado;
    /**
     * Creates new form TelaProfessor
     */
    public TelaAtividade(Turma turma) {
        initComponents();
        this.turmaSelecionada = turma;
        this.professorLogado = turma.getProfessor();
        carregarAtividades();
    txtNomeTurma.setEditable(false);
    txtNomeTurma.setText(turmaSelecionada.getNome());
    
    txtNomeProfessor.setEditable(false);
    txtNomeProfessor.setText(turmaSelecionada.getProfessor().getNome());
    
    
    
    }
    
    private void carregarAtividades() {
    try {
        AtividadeDAO dao = new AtividadeDAO();
        List<Atividade> lista = dao.listarAtividadesPorTurma(
            turmaSelecionada.getIdturma(),
            turmaSelecionada.getProfessor().getIdProfessor()
        );

        DefaultTableModel modelo = (DefaultTableModel) tabelaAtividade.getModel();
        modelo.setRowCount(0); // limpa tabela

        for (Atividade a : lista) {
            modelo.addRow(new Object[]{a.getNome(), a.getDescricao()});
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar atividades: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel01_TelaProfessor = new javax.swing.JPanel();
        jPanel02_TelaProfessor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAtividade = new javax.swing.JTable();
        btnCadastrarAtividade = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNomeTurma = new javax.swing.JTextField();
        txtNomeProfessor = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel01_TelaProfessor.setBackground(new java.awt.Color(0, 102, 255));
        jPanel01_TelaProfessor.setForeground(new java.awt.Color(0, 102, 255));

        jPanel02_TelaProfessor.setBackground(new java.awt.Color(255, 255, 255));
        jPanel02_TelaProfessor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaAtividade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero", "Nome"
            }
        ));
        jScrollPane1.setViewportView(tabelaAtividade);

        jPanel02_TelaProfessor.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 580, 330));

        btnCadastrarAtividade.setBackground(new java.awt.Color(0, 102, 255));
        btnCadastrarAtividade.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        btnCadastrarAtividade.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarAtividade.setActionCommand("Cadastrar Atividades");
        btnCadastrarAtividade.setLabel("Cadastrar Atividades");
        btnCadastrarAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAtividadeActionPerformed(evt);
            }
        });
        jPanel02_TelaProfessor.add(btnCadastrarAtividade, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 150, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Turma:");
        jPanel02_TelaProfessor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        txtNomeTurma.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtNomeTurma.setBorder(null);
        txtNomeTurma.setFocusable(false);
        jPanel02_TelaProfessor.add(txtNomeTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 310, -1));

        txtNomeProfessor.setBackground(new java.awt.Color(0, 102, 255));
        txtNomeProfessor.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtNomeProfessor.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeProfessor.setBorder(null);
        txtNomeProfessor.setFocusable(false);
        txtNomeProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProfessorActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(0, 102, 255));
        btnSair.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.setBorder(null);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(0, 102, 255));
        btnVoltar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(null);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel01_TelaProfessorLayout = new javax.swing.GroupLayout(jPanel01_TelaProfessor);
        jPanel01_TelaProfessor.setLayout(jPanel01_TelaProfessorLayout);
        jPanel01_TelaProfessorLayout.setHorizontalGroup(
            jPanel01_TelaProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel01_TelaProfessorLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel01_TelaProfessorLayout.createSequentialGroup()
                .addComponent(jPanel02_TelaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel01_TelaProfessorLayout.setVerticalGroup(
            jPanel01_TelaProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel01_TelaProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel01_TelaProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel02_TelaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel01_TelaProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel01_TelaProfessor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProfessorActionPerformed
       
    }//GEN-LAST:event_txtNomeProfessorActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        
        TelaLogin l = new TelaLogin();
        l.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastrarAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAtividadeActionPerformed
        // TODO add your handling code here:
        
        TelaCadastroAtividade telaCadastro = new TelaCadastroAtividade(turmaSelecionada);
        telaCadastro.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_btnCadastrarAtividadeActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        
        TelaProfessor p = new TelaProfessor(professorLogado);
        p.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarAtividade;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel01_TelaProfessor;
    private javax.swing.JPanel jPanel02_TelaProfessor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaAtividade;
    private javax.swing.JTextField txtNomeProfessor;
    private javax.swing.JTextField txtNomeTurma;
    // End of variables declaration//GEN-END:variables
}
