/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

/**
 *
 * @author Usuario
 */
public class TelaAtividade extends javax.swing.JFrame {

    /**
     * Creates new form TelaProfessor
     */
    public TelaAtividade() {
        initComponents();
        
    txtNomeProfessor.setEditable(false); // Impede digitação
    txtNomeProfessor.setText("Nome do Professor"); // Texto exibido
    
    txtNomeTurma.setEditable(false); // Impede digitação
    txtNomeTurma.setText("Desenvolvimento de Sistema"); 
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel01_TelaProfessor = new javax.swing.JPanel();
        jPanel02_TelaProfessor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCadastrarAtividade = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        txtNomeTurma = new javax.swing.JTextField();
        txtNomeProfessor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel01_TelaProfessor.setBackground(new java.awt.Color(0, 102, 255));
        jPanel01_TelaProfessor.setForeground(new java.awt.Color(0, 102, 255));

        jPanel02_TelaProfessor.setBackground(new java.awt.Color(255, 255, 255));
        jPanel02_TelaProfessor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero", "Nome"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel02_TelaProfessor.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 580, 330));

        btnCadastrarAtividade.setBackground(new java.awt.Color(0, 102, 255));
        btnCadastrarAtividade.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        btnCadastrarAtividade.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarAtividade.setActionCommand("Cadastrar Atividades");
        btnCadastrarAtividade.setLabel("Cadastrar Atividades");
        btnCadastrarAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAtividadeActionPerformed(evt);
            }
        });
        jPanel02_TelaProfessor.add(btnCadastrarAtividade, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 150, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Turma:");
        jPanel02_TelaProfessor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        btnExcluir.setText("Excluir");
        jPanel02_TelaProfessor.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnAlterar.setText("Alterar");
        jPanel02_TelaProfessor.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        txtNomeTurma.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtNomeTurma.setBorder(null);
        txtNomeTurma.setFocusable(false);
        jPanel02_TelaProfessor.add(txtNomeTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 310, -1));

        txtNomeProfessor.setBackground(new java.awt.Color(0, 102, 255));
        txtNomeProfessor.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtNomeProfessor.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeProfessor.setBorder(null);
        txtNomeProfessor.setFocusable(false);
        txtNomeProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProfessorActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sair");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel01_TelaProfessorLayout = new javax.swing.GroupLayout(jPanel01_TelaProfessor);
        jPanel01_TelaProfessor.setLayout(jPanel01_TelaProfessorLayout);
        jPanel01_TelaProfessorLayout.setHorizontalGroup(
            jPanel01_TelaProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel01_TelaProfessorLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel01_TelaProfessorLayout.createSequentialGroup()
                .addComponent(jPanel02_TelaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel01_TelaProfessorLayout.setVerticalGroup(
            jPanel01_TelaProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel01_TelaProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel01_TelaProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel02_TelaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel01_TelaProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel01_TelaProfessor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProfessorActionPerformed
       
    }//GEN-LAST:event_txtNomeProfessorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCadastrarAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAtividadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarAtividadeActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtividade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrarAtividade;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel01_TelaProfessor;
    private javax.swing.JPanel jPanel02_TelaProfessor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtNomeProfessor;
    private javax.swing.JTextField txtNomeTurma;
    // End of variables declaration//GEN-END:variables
}
