/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import modelo.Professor;

/**
 *
 * @author Usuario
 */
public class TelaProfessor extends javax.swing.JFrame {
private Professor professorLogado;
    /**
     * Creates new form TelaProfessor
     */
    public TelaProfessor(Professor logado) {
        initComponents();
        
    this.professorLogado = logado;

    txtNomeProfessor.setEditable(false);
    txtNomeProfessor.setText(professorLogado.getNome());

    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel01_TelaProfessor = new javax.swing.JPanel();
        jPanel02_TelaProfessor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCdastrarTurma = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        txtNomeProfessor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel01_TelaProfessor.setBackground(new java.awt.Color(0, 102, 255));
        jPanel01_TelaProfessor.setForeground(new java.awt.Color(0, 102, 255));

        jPanel02_TelaProfessor.setBackground(new java.awt.Color(255, 255, 255));
        jPanel02_TelaProfessor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero", "Nome"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel02_TelaProfessor.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 580, 330));

        btnCdastrarTurma.setBackground(new java.awt.Color(0, 102, 255));
        btnCdastrarTurma.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        btnCdastrarTurma.setForeground(new java.awt.Color(255, 255, 255));
        btnCdastrarTurma.setText("Cadastrar Turma");
        btnCdastrarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCdastrarTurmaActionPerformed(evt);
            }
        });
        jPanel02_TelaProfessor.add(btnCdastrarTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 130, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Turmas:");
        jPanel02_TelaProfessor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        btnExcluir.setBackground(new java.awt.Color(0, 102, 255));
        btnExcluir.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        jPanel02_TelaProfessor.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnAlterar.setBackground(new java.awt.Color(0, 102, 255));
        btnAlterar.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        jPanel02_TelaProfessor.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        btnVisualizar.setBackground(new java.awt.Color(0, 102, 255));
        btnVisualizar.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        btnVisualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizar.setText("Visualizar");
        jPanel02_TelaProfessor.add(btnVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        txtNomeProfessor.setBackground(new java.awt.Color(0, 102, 255));
        txtNomeProfessor.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtNomeProfessor.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeProfessor.setBorder(null);
        txtNomeProfessor.setFocusable(false);
        txtNomeProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProfessorActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sair");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel01_TelaProfessorLayout = new javax.swing.GroupLayout(jPanel01_TelaProfessor);
        jPanel01_TelaProfessor.setLayout(jPanel01_TelaProfessorLayout);
        jPanel01_TelaProfessorLayout.setHorizontalGroup(
            jPanel01_TelaProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel01_TelaProfessorLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel01_TelaProfessorLayout.createSequentialGroup()
                .addComponent(jPanel02_TelaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel01_TelaProfessorLayout.setVerticalGroup(
            jPanel01_TelaProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel01_TelaProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel01_TelaProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel02_TelaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel01_TelaProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel01_TelaProfessor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProfessorActionPerformed
       
    }//GEN-LAST:event_txtNomeProfessorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCdastrarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCdastrarTurmaActionPerformed
        
        TelaCadastroTurma t = new TelaCadastroTurma(professorLogado);
        t.setVisible(true);
    }//GEN-LAST:event_btnCdastrarTurmaActionPerformed
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCdastrarTurma;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel01_TelaProfessor;
    private javax.swing.JPanel jPanel02_TelaProfessor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtNomeProfessor;
    // End of variables declaration//GEN-END:variables
}
